name: Docker Image CI

on:
  push:
    branches: [ "development" ]

jobs:

  build:

    # It includes docker runtime
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Poller
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/agent:3.3.3 -f ./poller/Dockerfile -- push .
      
      - name: Build and push basic Poller
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/basicagent:3.3.3 -f ./pollerbasic/Dockerfile -- push .
