name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    # It includes docker runtime
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file poller/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/agent:3.3.3

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file pollerbasic/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/basicagent:3.3.3
